config/routes.rb
Rails.application.routes.draw do
  

  resources :tasks do
    member do
      post 'done'
      post 'pending'
    end
  end

  resources :workers

  root 'tasks#index'
end

app/models/task.rb
class Task < ActiveRecord::Base

  # Esto significa que una instancia de Task solo puede estar relacionada con una instancia de Worker y al revés
  # has_one :worker

  # Esta relación permite que varias instancias de Task tengan asociada la misma instancia de Worker
  belongs_to :worker

  # Validaciones
  # Más info : http://guides.rubyonrails.org/active_record_validations.html
  validates :name, 
    presence: true, 
    uniqueness: true, 
    length: { in: 6..20 }
  validates :worker_id, 
    presence: { message: "Debes asociar un trabajador a la tarea" }
  #validate :worker_exists, on: [:create, :update]

  def worker_name; worker && worker.name; end
  def done!; self.update(done: true); end
  def pending!; self.update(done: false); end
  def status; done? ? 'done' : 'pending'; end

  private

  def worker_exists
    errors.add(:worker_id, 'no existe') unless Worker.exists?(self.worker_id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :done, :pending]
  # Cargar los workers que se van a mostrar en el desplegable del formulario
  before_action :set_workers, only: [:new, :edit, :update]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to :root, notice: 'Task was successfully created.' }
        #
        # ¿ Por qué no renderizamos el index y listo ?
        #
        # format.html { render :index, notice: 'Task was successfully created.' }
        #
        # Por que render simplemente lo que hace es mostrar la plantilla que le indicamos usando las
        #   variables que se han cargado hasta este momento en la acción en curso. 
        # Si rendeamos :index, @tasks no está establecido por que establece cuando ejecutamos 
        #   la acción :index ( línea 9 ). 
        
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to root_url, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /tasks/1/done
  # POST /tasks/1/done.json
  def done
    # @task = Task.find(params[:id])
    # Esto lo podemos hacer incluyendo la accion :done en before_action :set_task
    @task.done!
    respond_to do |format|
      format.html { redirect_to :tasks, notice: "Task #{@task.name} is done!" }
      format.json { render :show, status: :ok, location: @task }
    end
  end

  # POST /tasks/1/pending
  # POST /tasks/1/pending.json
  def pending
    # @task = Task.find(params[:id])
    # Esto lo podemos hacer incluyendo la accion :pending en before_action :set_task
    @task.pending!
    respond_to do |format|
      format.html { redirect_to :tasks, notice: "Task #{@task.name} is not done yet!" }
      format.json { render :show, status: :ok, location: @task }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      # Añadimos el parámetro worker_id a los parámetros permitidos
      params.require(:task).permit(:name, :done, :worker_id)
    end

    def set_workers
      @workers  = Worker.all.map{|w| [w.name, w.id]}
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :done %>
  </div>

  <!-- Campo para vincular un Worker a Task -->
  <div class="field">
    <%= f.label :worker_id %><br>
    <%= f.select :worker_id, @workers, include_blank: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Done</th>
      <th>Worker</th>
      <th>Updated at</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr class="<%= task.status %>">
        <td><%= task.name %></td>
        <td><%= task.status %></td>
        <td><%= task.worker_name %></td>
        <td><%= I18n.l task.updated_at, format: :short %></td>
        <td>
          <%= link_to 'Done!', done_task_path(task), method: :post unless task.done? %>
          <%= link_to 'Undo :(', pending_task_path(task), method: :post if task.done? %>
        </td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="add-new">
  <%= link_to 'New Task', new_task_path %>
  <%#= button_to 'New Task', new_task_path, { method: :get } %>
</div>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Done:</strong>
  <%= @task.done %>
</p>

<p>
  <strong>Worker:</strong>
  <!-- 
    Evitar llamadas anidadas entre modelos en las vistas.
    En este caso, worker puede estar vacío, por lo que la llamada a name produce un error
    undefined method `name' for nil:NilClass
    <%#= @task.worker.name %>
  -->
  <%= @task.worker_name %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>