config/routes.rb
Rails.application.routes.draw do
  

  resources :tasks do
    member do
      post 'done'
      post 'pending'
    end
  end

  resources :workers

  root 'tasks#index'
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  validates :name, 
    presence: true, 
    uniqueness: true, 
    format: { with: /\A[a-z0-9]+\z/ }
  
  has_many :task

  # Si en lugar de detener el grabado de datos queremos controlarlos para acomodarlos a nuestas
  #   especificaciones, podemos realizar transformaciones de los datos antes de la validación 
  # before_validation :name_to_downcase

  # private

  # def name_to_downcase
  #   self.name.downcase!
  # end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController

  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to :tasks, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:name)
    end
end

app/views/workers/_form.html.erb
<%= form_for(@worker) do |f| %>
  <% if @worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
      <% @worker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workers/edit.html.erb
<h1>Editing worker</h1>

<%= render 'form' %>

<%= link_to 'Show', @worker %> |
<%= link_to 'Back', workers_path %>

app/views/workers/index.html.erb
<h1 class="title">Listing workers</h1>

<table class="small-table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workers.each do |worker| %>
      <tr>
        <td><%= worker.name %></td>
        <td><%= link_to 'Show', worker %></td>
        <td><%= link_to 'Edit', edit_worker_path(worker) %></td>
        <td><%= link_to 'Destroy', worker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="add-new">
  <%= link_to 'New Worker', new_worker_path %>
  <%#= button_to 'New Worker', new_worker_path, { method: :get } %>
</div>

app/views/workers/new.html.erb
<h1>New worker</h1>

<%= render 'form' %>

<%= link_to 'Back', workers_path %>

app/views/workers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @worker.name %>
</p>

<%= link_to 'Edit', edit_worker_path(@worker) %> |
<%= link_to 'Back', workers_path %>